## 数据操作实现

In [9]:
import torch
import warnings
warnings.filterwarnings("ignore")

In [7]:
# 张量表示一个数值组成的数组，这个数组可能有多个维度
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [8]:
# 可以通过张量的 shape 属性来访问张量的形状和张量中元素的总数 
x.shape

torch.Size([12])

In [9]:
x.numel()

12

In [10]:
# 要改变一个张量的形状而不改变元素数量和元素值，可以调用 reshape 函数
X = x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [11]:
# 使用全0，1，其他常量或者从特定分布中随机采样的数字
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
# 通过提供包含数值的 Python 列表（或嵌套列表）来维所需张量中每一个元素赋予确定值
torch.tensor([[2, 1, 4, 3],[1, 2, 3, 4],[4, 2, 1, 0]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 2, 1, 0]])

In [14]:
# 常见的标准算术运算符（+-*/和**） 都可以被升级按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
# 按元素方法应用更多的计算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [16]:
# 将多个张量连结在一起
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3],[1, 2, 3, 4],[4, 3, 2, 1]])
torch.cat((X, Y),dim=0), torch.cat((X, Y), dim=1)  # dim=0 按行堆在一起，dim=1 按列堆在一起

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
# 通过 逻辑运算符构建二元张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
# 对张量中的所有元素进去求和会产生一个只有一个元素的张量
X.sum()

tensor(66.)

In [19]:
# 即使形状不同，我们仍然可以通过调用 广播机制 broadcastring mechanism 来执行按元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b  # 明显 a,b 矩阵形状不同，无法加减，通过广播机制 将 a 变为3*2，将b变为3*2，再计算

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [21]:
# 可以用[-1]选择最后一个元素，可以用[1:3] 选择第二个和第三个元素
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
# 除读取外，我们还可以通过指定索引来将元素写入矩阵
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
# 为多个元素赋值相同的值，我们只需要索引所有元素，然后为它赋值
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [26]:
# 运行一些操作可能会导致为新结果分配内存
before = id(Y)  # 类似指针
Y = Y + X
id(Y) == before

False

In [29]:
# 执行原地操作
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y # 对X的内容进行改写，但指针没有发生变化
print('id(Z):', id(Z))

id(Z): 2345167432416
id(Z): 2345167432416


In [32]:
# 如果在后续计算中没有重复使用 X，我们也可以使用X[:] = X + Y 或者 X+=Y 来减少操作的内存开销
before = id(X)
X += Y  # 本质是 += 调用 append 方法
id(X) == before

True

In [33]:
# 转换为 NumPy 张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [35]:
# 将大小为1的张量转化为 Python 标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 数据预处理实现

In [4]:
# 创建一个人工数据集，并存储在csv（逗号分隔值）文件
import os 
os.makedirs(os.path.join('..', 'data'),exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n')       # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4.0,NA,178100\n')
    f.write('NA,NA,14000\n')

In [5]:
# 从创建的 csv 文件中加载原始数据集
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN   14000

In [11]:
# 为了处理缺失的数据，经典的方法包括 插值和删除，这里我们将插值
inputs, outputs = data.iloc[:, 0:2],data.iloc[:, 2]   # [:,2] 表示取所有行的第3列，冒号表示取所有行，逗号后的数字2表示取第3列
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [12]:
# 对于 inputs 中类别值或离散值，我们将 "NAN" 视为一个类别
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [13]:
# 现在 inputs 和 outpus 中的所有条目都是数值类型，他们可以转化为张量格式
X, Y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, Y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100,  14000]))