In [ ]:
# 标量：单独的树 
# 向量：特殊的张量，只有一维 
# 张量：多维数组

In [1]:
# 标量由只有一个元素的张量表示
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [4]:
# 你可以将向量视为标量值组成的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
# 通过张量的索引来访问任一元素
x[3]

tensor(3)

In [6]:
# 访问张量的长度
len(x)

4

In [8]:
# 只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

In [9]:
# 通过指定两个分量m和n来创建一个形状为 m*n 的矩阵
A = torch.arange(20).reshape(5, 4)
A 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
# 对称矩阵 A = A^T
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [16]:
# 就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
# 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都是将相同形状的张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新的内存，将 A 的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
# 两个矩阵的按元素乘法称为 哈达玛积 Hadamard product
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [21]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [31]:
# 计算其元素的和
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [26]:
# 表示任意形状张量的元素和
A = torch.arange(20*2).reshape(2,5,4)  # 20*2 就是 40 的意思
A, A.shape, A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 torch.Size([2, 5, 4]),
 tensor(780))

In [13]:
# 指定求和汇总张量的轴 
# 在 PyTorch 中，张量的轴是张量的特定维度
A_sum_axis0 = A.sum(axis=0)   # axis=0 表示沿着第一个维度（行）进行求和操作[汇成一行]
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

In [14]:
A_sum_axis1 = A.sum(axis=1) # axis=1 表示沿着第二维度（列）进行求和操作[汇成一列，但因为是二维，故行表示]
A, A_sum_axis1, A_sum_axis1.shape  

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [18]:
# 一个与求和相关的量是 平均值（mean或average）
A = A.to(torch.float)
A, A.mean(), A.sum() / A.numel()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(9.5000),
 tensor(9.5000))

In [16]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [24]:
# 计算总和或均值时保持轴数不变
# keepdims 是一个布尔值，表示是否保持控制维度，如果 keepdims 是False（默认值），那么张量的秩会在空间维度上减少，
# 如果 keepdims 是True，那么空间维度会保留，但长度为1 

sum_A = A.sum(axis=1, keepdims=True)  # 列汇和,若 keepdims是false则结果 ([6,22,38,54,70]) 一维，true 保持维度不变
A, sum_A

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]))

In [25]:
# 通过广播将 A 除以 sum
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [26]:
# 某个轴计算 A 元素的累加总和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [32]:
# 点积是相同位置的按元素乘积的和
y = torch.ones(4, dtype=torch.float32)
x, y 
# torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]))

In [33]:
# 我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x * y)

tensor(6.)

In [38]:
# 矩阵向量积 Ax 是长度为 m 的列向量，其 i^th 元素是点积 a_i^Tx
# 点积（也称为数量积或内积）是两个向量的乘积的和，结果是一个标量
# 向量积（也称为叉积）是两个向量的乘积，结果是一个向量

# 点积的计算方式是两个向量的模与其夹角的余弦值相乘。从几何角度看，点积是两个向量的长度与它们夹角余弦的积。从代数角度看，点积是对两个向量对应位置上的值相乘再相加的操作，其结果即为点积。3
# 向量积的计算方式是两个向量所在平面上形成的平行四边形面积，其方向垂直于这个平面。
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [39]:
# 我们可以将矩阵-矩阵乘法 AB 看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个 n*m 矩阵
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

$ \|\mathbf{x}\|_2=\sqrt{\sum_{i=1}^n x_i^2} $

In [40]:
# L_2 范式是向量元素平方和的平方根 
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$ \|\mathbf{x}\|_1=\sum_{i=1}^n\left|x_i\right| $

In [42]:
# L_1 范式是向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

$ \|\mathbf{X}\|_F=\sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{i j}^i} $

In [43]:
# 矩阵的 弗罗贝尼乌斯范式 Frobeninus norm 是矩阵元素的平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)